name: debugger-action

# 将触发方式改为手动触发
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Setup Debug Session
       uses: csexton/debugger-action@master
